name: simple_task_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter    
  stacked: ^3.4.0
  flutter_secure_storage: ^9.0.0
  stacked_services: ^1.1.0  
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  talker_dio_logger: ^2.3.1
  flutter_hooks: ^0.20.3
  google_fonts: 6.1.0
  flutter_svg: 2.0.10+1
  intl: ^0.18.1
  provider: ^6.0.5
  dartz: ^0.10.1
  bot_toast: ^4.1.3
  device_preview: ^1.1.0
  gap: ^3.0.1
  flutter_form_builder: ^9.2.1
  form_validator: ^2.1.1
  flutter_spinkit: ^5.2.0
  equatable:
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  scroll_to_index: ^3.0.1
 
  


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  stacked_generator: ^1.3.3
  mockito: ^5.4.1
  build_runner: ^2.4.9
  flutter_launcher_icons: "^0.13.1"
  hive_generator:
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets: 
    - assets/svg/
    - assets/png/




